# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CropdisV2',
                'doc_host': 'https://robeson1010.github.io',
                'git_url': 'https://github.com/robeson1010/CropdisV2',
                'lib_path': 'CropdisV2'},
  'syms': {'CropdisV2.core': {'CropdisV2.core.foo': ('core.html#foo', 'CropdisV2/core.py')}}}